name: CI
on:
  push: {}
  pull_request: {}
  workflow_dispatch: {}

jobs:
  oidc:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    strategy:
      fail-fast: false
      matrix:
        count: [0, 1] # , 2, 3, 4, 5, 6, 7, 8, 9, 10]
    steps:
      - uses: actions/checkout@v3
      - uses: depot/setup-action@v1
      - uses: depot/build-push-action@v1
