name: CI
on: push

permissions:
  contents: read
  id-token: write

jobs:
  oidc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: depot/setup-action@v1
      - run: depot build .
        env:
          DEPOT_EXPERIMENTAL_OIDC: 1
