name: CI
on:
  push: {}
  pull_request: {}
  workflow_dispatch: {}

jobs:
  oidc:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
      - uses: actions/checkout@v3
      - uses: depot/setup-action@v1
      - uses: depot/build-push-action@public-oidc
        env:
          INPUT: hello-world
        with:
          build-args: |
            INPUT=${INPUT}

#       - run: env
#       - run: cat $GITHUB_EVENT_PATH | jq -c .
#       - run: echo $JSON | jq .
#         env:
#           JSON: ${{ toJSON(github) }}
#       - run: |
#           while true; do
#             echo "Waiting for auth (0ed5c6ec-abd0-4d48-9ed9-888176abb2aa)"
#             sleep 5
#           done
#         timeout-minutes: 10
